# Values here will override previously loaded from default_settings.toml

[development]                    # All [environments] inherits values from [default] if defined
host_name = "localhost"
key_crt  = "..< location of your ssl/daemon/private_daemon.crt >"
private_daemon_key = "< location of your ssl/daemon/private_daemon.ke ?"
log_file = "log/app.log"
mqtt_header = "chia_wsocket_mqtt/"
mqtt_server = "xxx.xxx.xxx.xxx"
mqtt_port = "1883"
key_pashprase = "<Your Phase Phrase>"
[production]
host_name = "localhost"
key_crt  = "< location of your ssl/daemon/private_daemon.crt >"
private_daemon_key = "< location of your ssl/daemon/private_daemon.key >"
log_file = "log/app.log"
mqtt_header = "chia_ws"
mqtt_server = "xxx.xxx.xxx.xxx"
mqtt_port = 1883
key_pashprase = "<Your Phase Phrase>"

# NOW go and read the `configs/.secrets.toml` file
